language: scala
scala:
   - 2.10.6
   - 2.11.8
jdk:
  - oraclejdk7
  - openjdk7
env:
  global:
  - secure: M/f/K1H0pZS5rgeoQXroFJlz5t2l8UcP+Bogo2jn3drvrqdPB22Z0MzkorH9diBrtykGZmc3X0A8Y9SQob7YaJ+lD0XbSuwzM9TgAKHLg8CpJQffFpE0xUHybcrcdTnC19iiTI3vovr2nQzlYn31F0X0RXMSDyW0zOIDX9kDGuk=
  - secure: aEgUK6zpFDbDQNXVsJC9Y3CrvUTrbDci7U6mM/vR2/ksVL4dVMBCJAJsdXWwc12wIlYRNDrtuZ62/R+LbS8O1gjIeyU8hKhc81L8pfyJFOm9BztbN+4XqkPsXS7WqgpqI6lr1TABdHaHPwTCh5kFLtqkCD2NXMmi7uhmScJfVc0=
  - secure: LPO6f56t82laN2lzNuVuAIQkmkn8wOvmOzeu5ozYn9afJ+GGxjdJJ9TEYOQA5bZFKY/p6o65MemhlidhdMpZu++G1nVVdPoAh+NvEfesQxkQx0lFta6u2l2nKgUnpZL2mW8skM1LGepOyUZFujBAcSH6GHmQN0IP4zGVSrUvMX0=
script:
  - sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.8" && "${TRAVIS_JDK_VERSION}" == "oraclejdk7"' 
    tags: true
